import "@primer/css/dist/primer.css";
import "react-loading-skeleton/dist/skeleton.css";
import "./global.css";
import { ReactNode } from "react";
import { BaseStyles, ThemeProvider } from "@primer/react";
import { AuthProvider } from "@/context/AuthContext";
import { StyledComponentsRegistry } from "./registry";
import { SkeletonTheme } from "react-loading-skeleton";
import { FileProvider } from "@/context/FileContext";

export const metadata = {
  title: "Op’ton",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", type: "image/svg+xml", url: "/favicon.svg" },
    { rel: "icon", type: "image/x-icon", url: "/favicon.ico" },
  ],
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <BaseStyles>
              <SkeletonTheme baseColor='#f6f8fa' highlightColor='#d3dadf'>
                <AuthProvider>
                  <FileProvider>{children}</FileProvider>
                </AuthProvider>
              </SkeletonTheme>
            </BaseStyles>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
