import "@primer/css/dist/primer.css";
import './global.css'; 
import { ReactNode } from "react";
import { BaseStyles, ThemeProvider } from "@primer/react";
import { AuthProvider } from "@/context";

export const metadata = {
  title: "Opton",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <BaseStyles>
            <AuthProvider>{children}</AuthProvider>
          </BaseStyles>
        </ThemeProvider>
      </body>
    </html>
  );
}
