name: lint

on:
  pull_request:
    types:
      - opened        
      - synchronize   
      - reopened    
      - edited      

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: install dependencies
        run: npm install

      - name: run Lint
        run: npm run lint
        env:
          CI: true
